services:

  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  backend:
    image: ghcr.io/ryanfio15/ai-code-review-system-backend:latest
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
        
  frontend:
    image: ghcr.io/ryanfio15/ai-code-review-system-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
