services:

  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    networks:
      - db-net

  backend:
    image: ghcr.io/ryanfio15/ai-code-review-system-backend:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db-net
      - app-net

  frontend:
    image: ghcr.io/ryanfio15/ai-code-review-system-frontend:latest
    depends_on:
      - backend
    networks:
      - app-net

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - app-net


networks:
  db-net:
    driver: bridge
    internal: true
  app-net:
    driver: bridge

volumes:
  pgdata:
